<a href="https://colab.research.google.com/github/tadavarthi-rishi/Image-Classification-using-PyTorch/blob/master/Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline

In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[4.9157e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [6]:
#Construct a randomly initialized matrix:


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2335, 0.7608, 0.0262],
        [0.2733, 0.3441, 0.6101],
        [0.9659, 0.8489, 0.6427],
        [0.0138, 0.6415, 0.3587],
        [0.9240, 0.4089, 0.5905]])


In [8]:
#Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
#Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
#or create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.6874e+00,  1.3218e+00, -2.2984e+00],
        [ 5.1685e-02,  1.9099e+00,  1.7629e-01],
        [ 1.4233e-01,  1.0301e-01,  9.3885e-01],
        [-2.0625e-03, -2.2651e-01,  1.6662e+00],
        [-5.0965e-01,  2.9715e-01, -1.4852e-01]])


In [11]:
#Get its size:
print(x.size())

torch.Size([5, 3])


In [12]:
'''Note

``torch.Size`` is in fact a tuple, so it supports all tuple operations.
Operations ^^^^^^^^^^ There are multiple syntaxes for operations. In the following example, we will take a look at the addition operation.
Addition: syntax 1'''
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.4480,  1.8586, -2.0382],
        [ 0.2728,  2.0983,  0.2103],
        [ 0.7715,  0.9405,  1.0692],
        [ 0.5417,  0.3749,  2.2519],
        [ 0.3463,  0.7612,  0.7704]])


In [13]:
#Addition: syntax 2
print(torch.add(x, y))

tensor([[ 2.4480,  1.8586, -2.0382],
        [ 0.2728,  2.0983,  0.2103],
        [ 0.7715,  0.9405,  1.0692],
        [ 0.5417,  0.3749,  2.2519],
        [ 0.3463,  0.7612,  0.7704]])


In [14]:
#Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.4480,  1.8586, -2.0382],
        [ 0.2728,  2.0983,  0.2103],
        [ 0.7715,  0.9405,  1.0692],
        [ 0.5417,  0.3749,  2.2519],
        [ 0.3463,  0.7612,  0.7704]])


In [15]:
#Addition: in-place
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.4480,  1.8586, -2.0382],
        [ 0.2728,  2.0983,  0.2103],
        [ 0.7715,  0.9405,  1.0692],
        [ 0.5417,  0.3749,  2.2519],
        [ 0.3463,  0.7612,  0.7704]])


In [16]:
'''Note

Any operation that mutates a tensor in-place is post-fixed with an ``_``. For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.
You can use standard NumPy-like indexing with all bells and whistles!'''

print(x[:, 1])

tensor([ 1.3218,  1.9099,  0.1030, -0.2265,  0.2971])


In [17]:
#Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
#If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1496])
0.1496119499206543


In [19]:
'''NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.
The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.
Converting a Torch Tensor to a NumPy Array ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'''

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
#See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
#Converting NumPy Array to Torch Tensor ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ See how changing the np array changed the Torch Tensor automatically

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
'''All the Tensors on the CPU except a CharTensor support converting to NumPy and back.
CUDA Tensors
Tensors can be moved onto any device using the .to method.'''

# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!